{% set conda_forge_name = "python-marisa-trie" %}
{% set pypi_name = "marisa-trie" %}
{% set version = "0.7.4" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2a2258eacca9966325f9019378fc4621891f2482bc63e6441f70599595ed97d8" %}
{% set build = 1 %}

package:
  name: {{ conda_forge_name }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - pytest-runner

  run:
    - python

test:
  imports:
    - marisa_trie

about:
  home: https://github.com/pytries/marisa-trie
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Static memory-efficient & fast Trie-like structures for Python (based on marisa-trie C++ library)'
  dev_url: https://github.com/pytries/marisa-trie
  doc_url: https://marisa-trie.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - kmike
    - superbobry
