{% set conda_forge_name = "python-marisa-trie" %}
{% set pypi_name = "marisa-trie" %}
{% set version = "0.7.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "c73bc25d868e8c4ea7aa7f1e19892db07bba2463351269b05340ccfa06eb2baf" %}

package:
  name: {{ conda_forge_name }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - toolchain
    - pytest-runner

  run:
    - python

test:
  imports:
    - marisa_trie

about:
  home: https://github.com/pytries/marisa-trie
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Static memory-efficient & fast Trie-like structures for Python (based on marisa-trie C++ library)'
  dev_url: https://github.com/pytries/marisa-trie
  doc_url: https://marisa-trie.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - kmike
    - superbobry
