{% set version = "1.3.1" %}

package:
  name: marisa-trie
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/marisa-trie/marisa_trie-{{ version }}.tar.gz
  sha256: 97107fd12f30e4f8fea97790343a2d2d9a79d93697fe14e1b6f6363c984ff85b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python

test:
  imports:
    - marisa_trie

about:
  home: https://github.com/pytries/marisa-trie
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Static memory-efficient & fast Trie-like structures for Python (based on marisa-trie C++ library)
  dev_url: https://github.com/pytries/marisa-trie
  doc_url: https://marisa-trie.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kmike
    - superbobry
    - mariusvniekerk
