{% set version = "1.4.1" %}

package:
  name: marisa-trie
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/marisa-trie/marisa_trie-{{ version }}.tar.gz
  sha256: 44ce3bdbeb7c950d463e460184fc3e18702df9ef0edb826bac672fd789fb1d20

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools
  run:
    - python

test:
  imports:
    - marisa_trie
  commands:
    - pip check

about:
  home: https://github.com/pytries/marisa-trie
  license_file: LICENSE
  license: MIT AND (BSD-2-Clause OR LGPL-2.1-or-later)
  license_family: MIT
  summary: Static memory-efficient & fast Trie-like structures for Python (based on marisa-trie C++ library)
  dev_url: https://github.com/pytries/marisa-trie
  doc_url: https://marisa-trie.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kmike
    - superbobry
    - mariusvniekerk
