# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "l/Kku9jb9nIO3oTAPqk+JbnYDTsa0/HUIC06ma0LUvMn9dozz08cGfFJdP8rIsBy887tpKqZ/dPwgsZUqx9IX7N3iZllHw+jJFefZ14odTwyS8z9mrshkZO3MGkUGvw1i+Uic3B5t/yz4UOxg7B1KNqBiD9m/da2kdtzIkbfDe0QZLMQu2kwqIySoruJais0Y896261zdyPGWcHHJCf3uj6ASRybQzoAIFhkqOoErc2FfRX2FX1eeDUD0xtkfZCT6RccM8jVc7UY0S8wu9LrH+CPOQGV8Z4imnQET6eIQzNVGeX6dOQuAbZX5IkwnlSzZJxxJojD4FphsgZGYgys8nmiQtpW8lAaUsDLxdM9fwlnoBgwxftRfF+5CaePcmyDBs5QzKrpU2a0tTIhLEVrpwR0EiXMeOtLDG+mJ3mppogash68KJysuhmslOjQmzvq74hDavBZ6xXypSIf+X0fCsn/n0d3ZUteP+hs7CL//m9zu+6PUZ2HLu0E1zN39pZdmgV4Iuct75wqw1z0bFtxf5W8+TBbFOpz8ZvR3Zmxx4q54q2kINW5CXhMUcFlu15ry6tcusUS+/aW9HauGCAVhCD+xDrgCrzf7M6saXvy6Y8wpPVFqdfB/wvYqInAjCG9tSCLF7WdfHI9nW2mPxcOewfOdYmofX/HEq8anLGCqq0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
