# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: generic

os: osx

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "l/Kku9jb9nIO3oTAPqk+JbnYDTsa0/HUIC06ma0LUvMn9dozz08cGfFJdP8rIsBy887tpKqZ/dPwgsZUqx9IX7N3iZllHw+jJFefZ14odTwyS8z9mrshkZO3MGkUGvw1i+Uic3B5t/yz4UOxg7B1KNqBiD9m/da2kdtzIkbfDe0QZLMQu2kwqIySoruJais0Y896261zdyPGWcHHJCf3uj6ASRybQzoAIFhkqOoErc2FfRX2FX1eeDUD0xtkfZCT6RccM8jVc7UY0S8wu9LrH+CPOQGV8Z4imnQET6eIQzNVGeX6dOQuAbZX5IkwnlSzZJxxJojD4FphsgZGYgys8nmiQtpW8lAaUsDLxdM9fwlnoBgwxftRfF+5CaePcmyDBs5QzKrpU2a0tTIhLEVrpwR0EiXMeOtLDG+mJ3mppogash68KJysuhmslOjQmzvq74hDavBZ6xXypSIf+X0fCsn/n0d3ZUteP+hs7CL//m9zu+6PUZ2HLu0E1zN39pZdmgV4Iuct75wqw1z0bFtxf5W8+TBbFOpz8ZvR3Zmxx4q54q2kINW5CXhMUcFlu15ry6tcusUS+/aW9HauGCAVhCD+xDrgCrzf7M6saXvy6Y8wpPVFqdfB/wvYqInAjCG9tSCLF7WdfHI9nW2mPxcOewfOdYmofX/HEq8anLGCqq0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
