appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: xpbevatuaqREnb7QC3Hu4VZsoTL5ZVtighGqRBoF2ir9MOq0OpxUVFiP3FP4vtVNc7LLLjTYL+OSVOichHMUmkchIfwP4rtm1RUanfhuxg/s0dy6WAAUel9jW78HYDFNg4jlGj1qfV7gqDuLzTUgIslkvRu7uNneUd3VVnLWq6uNO2h0NRjabr8EK4svUArxE+vAF113mSVdL+oXH1WtCh2kJC/Nb1vpXOQpkuXi9fq72mRunY9vDRyxyauyTvTG+eAJRqDjXSet0Mvi3S4zr/LPNCoFcSG6/Eu5umPiNdXUCoydG55W5cib1NhGTYdSgKrxYFc+QHtk8ZbzNoQAvH62YytGzpLWjBfa5cFOZKVcW72CDzdhnh6Y8KMqed5cKccfNhhd1FmTlIW9LRvmDuKhjRXjGiFrqlhtyMNm2qRENSAmAuZfDj2st9eD70IAaSzqhYgHbR/zyyF/zANb5Ap7JfhLeVpbvKgsaB0MS9XlEoVMbs4qDqC7shmSpTIu0qSC7S8c7fIP7Y73w7F2rxdXZt3YjeymkiM0rgLYDlAIKlNcHXXZaqL7XxZm93+5rW91R4Y3rJjVtLp8hWvaYKKRacUsLEBnM+Q1V34MBLGHTuz/5fo15If673r3ysb+BjPEISN+XQEjies9Saij0hUhvQpOPJq/lteEJHJBKXI=}
