travis:
  secure:
    BINSTAR_TOKEN: lpnIDKEPDv0H5AauEumhqAiVXD6MfksTaLKdA+uR+XqkCql49NaZ1GFm54vKCIeLHcJrXAMFsYVQy2hpWjrwyzovv4Y3fXakQf8ROCHz3XrX4AQtFEtYlHDxYROG+pdi4j+JgXENk2H3ylRwRqgH2Ynq/MRmOm9EMOjqc2qbRIA5Euxh1E9euCMtT7Swga9T5vGUWUtI98rRbANOVMmF71Q9KrK6Q3ETw4U97ylgMCpXmkvwi3AlvnI4vEkNs/uXx5UFk9q3YKVXPE73fvmGuCfcR+LOhbZDfQJicvty/gpU0SusMlvil/Uw5KJrc2urK0Fnbg7h1zeb9jDmEKuWgAi10cz7EzYfHYFnJmcon6OQIuUXKERopNTjd/M+ws3WQMvFXgCYsD/PKCbrTmf3vcN1qCJAS2mOieSc38l+24Rwn2hkZRlkVP1Y9tu3lVu7FNNzYe0Xnt5Nt+katID6dupBHwg7+FNC62o7hThl+ycOhHOvinrnIxZLUCxCEb0A7dYYskkMDZj0Wmomjomo2X1OX/uijuV1ajW0uLGvYuDxvsa/0UeRiGcXJEigkJQLVWInEs9gSdknpN16KKs/wpKFM7WFAUUAtOAzLSLKtpEoUlXYSo/zk55yjA+SLCJow9G539vSBla50q33+st1ZUYm9kebE7dpwv1ynczF2rY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
